#!/bin/sh

# Bash configuration
export EDITOR="emacs"
export HISTSIZE=1000
export HISTFILESIZE=${HISTSIZE}
export HISTIGNORE="ls:cd:[bf]g:exit"
export HISTCONTROL="ignoreboth"
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=true
export LSCOLORS=ExGxFxdxCxDxDxBxBxExEx

# Options
shopt -s cdspell        # correct misspelled folders when cd
shopt -s checkwinsize   # reajust content width to window size
shopt -s cmdhist        # save multi-lines commands on one line
set show-all-if-ambiguous on  # single tab behavior

# Defines colors
txtreset='\[\e[0m'
blue="\[\e[01;34m\]"
orange="\[\e[02;33m\]"
green="\[\e[00;32m\]"
yellow="\[\e[01;33m\]"
lightblue="\[\033[1;36m\]"
bluegreen="\[\e[02;36m\]"
grey="\[\e[30;1m\]"

# To display current git branch in prompt
source ~/.git-prompt.sh

# Custom prompt
PS1="[\t] ${green}\u@\h${lightblue} \W \$${txtreset}\$(__git_ps1) "

# ssh host tab completion
complete -W "$(echo `cat ~/.ssh/known_hosts | cut -f 1 -d ' ' | sed -e s/,.*//g | uniq | grep -v "\["`;)" ssh

function mkcd() {
  FOLDER=$1
  mkdir -p $1
  cd $1
}

# Finally, load content within .bash.d
for file in $HOME/.bash.d/*; do
  test -f $file && source $file
done

# Load custom aliases if any
if [ -f $HOME/.alias ]; then
  . $HOME/.alias
fi
