#!/bin/sh
# Load custom aliases if any
if [ -f $HOME/.alias ]; then
  . $HOME/.alias
fi

# Custom prompt
PS1='[\u] \W \$ '

# Bash configuration
export HISTSIZE=1000
export HISTFILESIZE=${HISTSIZE}
export HISTIGNORE="ls:cd:[bf]g:exit"
export HISTCONTROL="ignoreboth"

# Custom environment variables
if [ "`uname`" == "Darwin" ]; then
  export PATH="${PATH}\
:/Users/adrien/Development/Pypy/pypy-1.9/bin\
:/Users/adrien/Development/Scala/sbt/bin\
:/Users/adrien/Development/Scala/scala/bin"
  export JAVA_HOME=/Library/Java/JavaVirtualMachines/1.6.0_33-b03-424.jdk/Contents/Home/

  # Ruby extension
  PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
  source /Users/adrien/.rvm/scripts/rvm
fi

function mkcd() {
  FOLDER=$1
  mkdir -p $1
  cd $1
}

