#!/bin/sh
# Load custom aliases if any
if [ -f $HOME/.alias ]; then
  . $HOME/.alias
fi

# Bash configuration
export HISTSIZE=1000
export HISTFILESIZE=${HISTSIZE}
export HISTIGNORE="ls:cd:[bf]g:exit"
export HISTCONTROL="ignoreboth"

# Options
shopt -s cdspell        # correct misspelled folders when cd
shopt -s checkwinsize   # reajust content width to window size
shopt -s cmdhist        # save multi-lines commands on one line

# Defines colors
txtreset='\e[0m'
blue="\[\e[01;34m\]"
orange="\[\e[02;33m\]"
green="\[\e[00;32m\]"
yellow="\[\e[01;33m\]"
lightblue="\[\033[1;36m\]"
bluegreen="\[\e[02;36m\]"
grey="\[\e[30;1m\]"

# Custom prompt
PS1="[\t] ${green}\u@\h${lightblue} \W \$ ${txtreset}"

function mkcd() {
  FOLDER=$1
  mkdir -p $1
  cd $1
}
